version: "3.8"

services:
  lb:
    image: nginx:alpine
    container_name: lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - payment-network
    restart: unless-stopped

  rinhadebackend:
    image: ${DOCKER_REGISTRY-}rinhadebackend
    build:
      context: .
      dockerfile: RinhaDeBackend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=paymentdb;Username=postgres;Password=postgres
      - PaymentProcessors__Default=http://payment-processor-default:8080
      - PaymentProcessors__Fallback=http://payment-processor-fallback:8080
    depends_on:
      - postgres
      - payment-processor-1
      - payment-processor-2
    networks:
      - payment-network
      - payment-processor
    restart: unless-stopped

  rinhadebackend_replica:
    image: ${DOCKER_REGISTRY-}rinhadebackend
    build:
      context: .
      dockerfile: RinhaDeBackend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=paymentdb;Username=postgres;Password=postgres
      - PaymentProcessors__Default=http://payment-processor-default:8080
      - PaymentProcessors__Fallback=http://payment-processor-fallback:8080
    depends_on:
      - postgres
      - payment-processor-1
      - payment-processor-2
    networks:
      - payment-network
      - payment-processor
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network
    restart: unless-stopped

  payment-processor-1:
    image: zanfranceschi/payment-processor
    hostname: payment-processor-default
    ports:
      - "8001:8080"
    networks:
      - payment-processor
    restart: unless-stopped

  payment-processor-2:
    image: zanfranceschi/payment-processor
    hostname: payment-processor-fallback
    ports:
      - "8002:8080"
    networks:
      - payment-processor
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge
